# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSqzCKi_mb_0jJ24g4_CiPuNzNujFYct
"""


import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt

# ================= PAGE CONFIG =================
st.set_page_config(
    page_title="Churn Prediction Dashboard",
    page_icon="📊",
    layout="wide"
)

# ================= CUSTOM CSS =================
st.markdown("""
<style>

/* Main background */
body {
    background-color: #F5F7FA;
}

/* Sidebar gradient */
section[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #11998e, #38ef7d);
    color: white;
}

/* Button */
.stButton>button {
    background: linear-gradient(90deg, #11998e, #38ef7d);
    color: white;
    font-size: 16px;
    border-radius: 10px;
    height: 3em;
    width: 100%;
    border: none;
}

/* Header */
.header-box {
    background: linear-gradient(90deg, #11998e, #38ef7d);
    padding: 20px;
    border-radius: 12px;
    text-align: center;
    color: white;
    font-size: 28px;
    font-weight: bold;
}

/* Result cards */
.card {
    padding: 20px;
    border-radius: 12px;
    text-align: center;
    font-size: 20px;
    font-weight: bold;
}

.green {
    background-color: #d4edda;
    color: #155724;
}

.red {
    background-color: #f8d7da;
    color: #721c24;
}

</style>
""", unsafe_allow_html=True)

# ================= LOAD MODEL =================
model = joblib.load("churn_pipeline.pkl")

# ================= SIDEBAR =================
st.sidebar.title("📊 Dashboard")

st.sidebar.markdown("### 🧠 About")
st.sidebar.write("Predict customer churn using ML pipeline.")

st.sidebar.markdown("### ⚙️ Model Info")
st.sidebar.write("Model: Logistic / Random Forest")
st.sidebar.write("Dataset: Telco Churn")
st.sidebar.write("Accuracy: ~80-85%")

st.sidebar.markdown("### 📌 Tips")
st.sidebar.write("- Higher charges → higher churn risk")
st.sidebar.write("- Month-to-month users churn more")

st.sidebar.markdown("---")
st.sidebar.markdown("👨‍💻 Developed by You")

# ================= HEADER =================
st.markdown("""
<div class="header-box">
📊 Customer Churn Prediction Dashboard
</div>
""", unsafe_allow_html=True)

st.markdown("### 🚀 Enter Customer Details")

# ================= INPUT FORM =================
col1, col2, col3 = st.columns(3)

with col1:
    gender = st.selectbox("Gender", ["Male", "Female"])
    senior = st.selectbox("Senior Citizen", [0, 1])
    partner = st.selectbox("Partner", ["Yes", "No"])
    dependents = st.selectbox("Dependents", ["Yes", "No"])

with col2:
    tenure = st.slider("Tenure (months)", 0, 72, 12)
    phone = st.selectbox("Phone Service", ["Yes", "No"])
    internet = st.selectbox("Internet Service", ["DSL", "Fiber optic", "No"])
    contract = st.selectbox("Contract", ["Month-to-month", "One year", "Two year"])

with col3:
    monthly = st.number_input("Monthly Charges", 0.0, 200.0, 70.0)
    total = st.number_input("Total Charges", 0.0, 10000.0, 800.0)
    payment = st.selectbox("Payment Method", [
        "Electronic check", "Mailed check",
        "Bank transfer (automatic)", "Credit card (automatic)"
    ])

# ================= PREDICT =================
if st.button("🚀 Predict Churn"):

    input_data = pd.DataFrame([{
        "gender": gender,
        "SeniorCitizen": senior,
        "Partner": partner,
        "Dependents": dependents,
        "tenure": tenure,
        "PhoneService": phone,
        "MultipleLines": "No",
        "InternetService": internet,
        "OnlineSecurity": "No",
        "OnlineBackup": "No",
        "DeviceProtection": "No",
        "TechSupport": "No",
        "StreamingTV": "No",
        "StreamingMovies": "No",
        "Contract": contract,
        "PaperlessBilling": "Yes",
        "PaymentMethod": payment,
        "MonthlyCharges": monthly,
        "TotalCharges": total
    }])

    prediction = model.predict(input_data)[0]
    prob = model.predict_proba(input_data)[0]

    churn_prob = prob[1]
    no_churn_prob = prob[0]

    # ================= RESULT =================
    colA, colB = st.columns(2)

    with colA:
        if prediction == 1:
            st.markdown('<div class="card red">⚠️ High Risk of Churn</div>', unsafe_allow_html=True)
        else:
            st.markdown('<div class="card green">✅ Customer Likely to Stay</div>', unsafe_allow_html=True)

    with colB:
        st.metric("Churn Probability", f"{churn_prob:.2f}")

    # ================= GRAPH =================
    st.markdown("### 📊 Prediction Breakdown")

    fig, ax = plt.subplots(figsize=(3,2))
    ax.bar(["No Churn", "Churn"], [no_churn_prob, churn_prob])
    ax.set_title("Prediction Confidence")

    st.pyplot(fig)

# ================= FOOTER =================
st.markdown("---")
st.markdown("💡 Built with Scikit-learn Pipeline | Streamlit")

